title: "Exercise-8"
author: "Aldair Perez"
date: "03-21-2025"
format: html
execute: 
  echo: true

# Question 1
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

# Quesiton 2
```{r}
url <- 'https://raw.githubusercontent.com/nytimes/covid-19-data/refs/heads/master/us-counties-2020.csv'
covid_data <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/refs/heads/master/us-counties-2020.csv")
```

# Question 3
```{r}
covid_state_data <- merge(covid_data, state_df, by.x = "state", by.y = "state_name")
```

# Question 4
```{r}
covid_state_data <- covid_state_data %>%
  group_by(state_region, state, county) %>%
  arrange(date) %>%
  mutate(cumulative_cases = cumsum(cases),
         cumulative_deaths = cumsum(deaths)) %>%
  ungroup()
```

# Question 5
```{r}
covid_state_data_long <- covid_state_data %>%
  pivot_longer(cols = c(cases, deaths, cumulative_cases, cumulative_deaths),
               names_to = "case_type",
               values_to = "count")
```

# Question 6
```{r}
ggplot(covid_state_data_long, aes(x = date, y = count, color = case_type, group = case_type)) +
  geom_line() +
  facet_wrap(~ state_region, scales = "free_y") +
  labs(title = "COVID Cases and Deaths", subtitle = "Daily and Cumulative Cases/Deaths", x = "Date", y = "Count", color = "Case Type", caption = "Data Source: https://raw.githubusercontent.com/nytimes/covid-19-data/refs/heads/master/us-counties-2020.csv") +
  scale_color_manual(values = c("blue", "red", "green", "yellow")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    strip.text = element_text(size = 12))
```

